spring.application.name=jdev_erp_backend

#==== Banco de dados ====
spring.datasource.url=jdbc:postgresql://localhost:5432/jdeverp
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=450

#==== Contexto ====
server.servlet.context-path=/jdeverp


spring.security.user.name=admin

spring.security.user.password=admin